version: "3.4"
services:
  logatechapi:
    container_name: "logatechapi"
    build:
      context: .
      dockerfile: "Dockerfile"
      cache_from: 
        - rust:latest
    links:
      - "postgres"
    depends_on:
      - "postgres"
    environment:
      - PG_URL=postgres://docker:docker@postgres:5432/docker
    networks:
      - logatechapi
    tty: true
    ports:
      - "4000:4000"
    
  postgres:
    image: postgres:alpine
    volumes:
      - pg_actix:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "docker" 
      POSTGRES_PASSWORD: "docker"
      PGPASSWORD: "docker"
    networks:
      - logatechapi
    ports:
      - "5432:5432"

networks:
  logatechapi:
    driver: bridge

volumes:
    pg_actix:
        driver: local